-- MySQL Script generated by MySQL Workbench
-- Fri 24 Oct 2025 04:26:25 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fullstack_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fullstack_project` ;

-- -----------------------------------------------------
-- Schema fullstack_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstack_project` ;
USE `fullstack_project` ;

-- -----------------------------------------------------
-- Table `fullstack_project`.`tunes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fullstack_project`.`tunes` ;

CREATE TABLE IF NOT EXISTS `fullstack_project`.`tunes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wheel_radius` FLOAT UNSIGNED NOT NULL DEFAULT 0.55,
  `wheel_width` FLOAT UNSIGNED NOT NULL DEFAULT 0.6,
  `wheel_offset` FLOAT NOT NULL DEFAULT -0.2,
  `wheel_vertical_offset` FLOAT NOT NULL DEFAULT -0.64,
  `wheel_longitudal_offset` FLOAT NOT NULL DEFAULT 0.4,
  `max_steering_angle` INT UNSIGNED NOT NULL DEFAULT 45,
  `suspension_lenght_min` FLOAT UNSIGNED NOT NULL DEFAULT 0.4,
  `suspension_lenght_max` FLOAT UNSIGNED NOT NULL DEFAULT 1,
  `suspension_preload` FLOAT NOT NULL DEFAULT 1,
  `suspension_damping` FLOAT NOT NULL DEFAULT 1,
  `suspension_stiffness` FLOAT NOT NULL DEFAULT 1,
  `front_tyre_lateral_friction` FLOAT UNSIGNED NOT NULL DEFAULT 15,
  `front_tyre_longitudal_friction` FLOAT UNSIGNED NOT NULL DEFAULT 1,
  `rear_tyre_lateral_friction` FLOAT UNSIGNED NOT NULL DEFAULT 2,
  `rear_tyre_longitudal_friction` FLOAT UNSIGNED NOT NULL DEFAULT 15,
  `four_wheel_drive` TINYINT NOT NULL DEFAULT 0,
  `antirollbar` TINYINT NOT NULL DEFAULT 1,
  `torque_split_ratio` FLOAT NOT NULL DEFAULT 1.4,
  `differential_limited_slip_ratio` FLOAT NOT NULL DEFAULT 1.3,
  `max_engine_torque` FLOAT UNSIGNED NOT NULL DEFAULT 2500,
  `clutch_strenght` FLOAT UNSIGNED NOT NULL DEFAULT 1000,
  `min_rpm` FLOAT UNSIGNED NOT NULL DEFAULT 400,
  `max_rpm` FLOAT UNSIGNED NOT NULL DEFAULT 8000,
  `damper_mass` FLOAT UNSIGNED NOT NULL DEFAULT 1,
  `flywheel_mass` FLOAT UNSIGNED NOT NULL DEFAULT 1,
  `vehicle_mass` FLOAT UNSIGNED NOT NULL DEFAULT 1200,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstack_project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fullstack_project`.`users` ;

CREATE TABLE IF NOT EXISTS `fullstack_project`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(24) NOT NULL,
  `email` VARCHAR(255) NULL,
  `hashed_password` VARCHAR(60) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `saved_tune_id` INT NOT NULL DEFAULT 1,
  `saved_location_id` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_tune1_idx` (`saved_tune_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_tune1`
    FOREIGN KEY (`saved_tune_id`)
    REFERENCES `fullstack_project`.`tunes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fullstack_project`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fullstack_project`.`players` ;

CREATE TABLE IF NOT EXISTS `fullstack_project`.`players` (
  `id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `player_name` VARCHAR(24) CHARACTER SET 'binary' NULL,
  `create_time` TIMESTAMP NULL,
  `last_active` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_player_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `fullstack_project`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstack_project`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fullstack_project`.`locations` ;

CREATE TABLE IF NOT EXISTS `fullstack_project`.`locations` (
  `players_id` INT NOT NULL,
  `position_x` FLOAT NOT NULL DEFAULT 0,
  `position_y` FLOAT NOT NULL DEFAULT 0,
  `position_z` FLOAT NOT NULL DEFAULT 0,
  `rotation_x` FLOAT NOT NULL DEFAULT 0,
  `rotation_y` FLOAT NOT NULL DEFAULT 0,
  `rotation_z` FLOAT NOT NULL DEFAULT 0,
  `rotation_w` FLOAT NOT NULL DEFAULT 1,
  `velocity_x` FLOAT NOT NULL DEFAULT 0,
  `velocity_y` FLOAT NOT NULL DEFAULT 0,
  `velocity_z` FLOAT NOT NULL DEFAULT 0)
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `fullstack_project`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fullstack_project`.`sessions` ;

CREATE TABLE IF NOT EXISTS `fullstack_project`.`sessions` (
  `token` CHAR(43) NOT NULL,
  `data` BLOB NOT NULL,
  `expiry` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`token`),
  INDEX `sessions_expiry_idx` (`expiry` ASC) VISIBLE)
ENGINE = InnoDB;

USE `fullstack_project`;

DELIMITER $$

USE `fullstack_project`$$
DROP TRIGGER IF EXISTS `fullstack_project`.`players_BEFORE_UPDATE` $$
USE `fullstack_project`$$
CREATE DEFINER = CURRENT_USER TRIGGER `fullstack_project`.`players_BEFORE_UPDATE` BEFORE UPDATE ON `players` FOR EACH ROW
BEGIN
    SET NEW.last_active = CURRENT_TIMESTAMP;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
