-- MySQL Script generated by MySQL Workbench
-- Fri 03 Oct 2025 04:07:01 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fullstack-project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullstack-project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstack-project` ;
USE `fullstack-project` ;

-- user
CREATE USER IF NOT EXISTS 'client'@'%' IDENTIFIED BY 'pass';
GRANT SELECT, INSERT, UPDATE, DELETE ON fullstack-project.* TO 'client'@'%';
FLUSH PRIVILEGES;

-- sessions
CREATE TABLE sessions (
   token CHAR(43) PRIMARY KEY,
   data BLOB NOT NULL,
   expiry TIMESTAMP(6) NOT NULL,
);
CREATE INDEX sessions_expiry_idx ON sessions (expiry);

-- -----------------------------------------------------
-- Table `fullstack-project`.`tunes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack-project`.`tunes` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `wheel_radius` FLOAT UNSIGNED NOT NULL DEFAULT 0.55,
  `wheel_width` FLOAT UNSIGNED NOT NULL DEFAULT 0.6,
  `wheel_offset` FLOAT NOT NULL DEFAULT -0.2,
  `wheel_vertical_offset` FLOAT NOT NULL DEFAULT -0.64,
  `wheel_longitudal_offset` FLOAT NOT NULL DEFAULT 0.4,
  `max_steering_angle` INT UNSIGNED NOT NULL DEFAULT 45,
  `suspension_lenght_min` FLOAT UNSIGNED NOT NULL DEFAULT 0.4,
  `suspension_lenght_max` FLOAT UNSIGNED NOT NULL DEFAULT 1,
  `suspension_preload` FLOAT NOT NULL DEFAULT 1,
  `suspension_damping` FLOAT NOT NULL DEFAULT 1,
  `suspension_stiffness` FLOAT NOT NULL DEFAULT 1,
  `front_tyre_lateral_friction` FLOAT UNSIGNED NOT NULL DEFAULT 15,
  `front_tyre_longitudal_friction` FLOAT UNSIGNED NOT NULL DEFAULT 1,
  `rear_tyre_lateral_friction` FLOAT UNSIGNED NOT NULL DEFAULT 2,
  `rear_tyre_longitudal_friction` FLOAT UNSIGNED NOT NULL DEFAULT 15,
  `four_wheel_drive` TINYINT NOT NULL DEFAULT 0,
  `antirollbar` TINYINT NOT NULL DEFAULT 1,
  `torque_split_ratio` FLOAT NOT NULL DEFAULT 1.4,
  `differential_limited_slip_ratio` FLOAT NOT NULL DEFAULT 1.3,
  `max_engine_torque` FLOAT UNSIGNED NOT NULL DEFAULT 2500,
  `clutch_strenght` FLOAT UNSIGNED NOT NULL DEFAULT 1000,
  `min_rpm` FLOAT UNSIGNED NOT NULL DEFAULT 400,
  `max_rpm` FLOAT UNSIGNED NOT NULL DEFAULT 8000,
  `damper_mass` FLOAT UNSIGNED NOT NULL DEFAULT 1,
  `flywheel_mass` FLOAT UNSIGNED NOT NULL DEFAULT 1,
  `vehicle_mass` FLOAT UNSIGNED NOT NULL DEFAULT 1200,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstack-project`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack-project`.`users` (
  `id` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `hashed_password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_location` POINT NOT NULL,
  `saved_tune_id` INT UNIQUE NOT NULL,
  PRIMARY KEY (`id`, `saved_tune_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_tune1_idx` (`saved_tune_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_tune1`
    FOREIGN KEY (`saved_tune_id`)
    REFERENCES `fullstack-project`.`tunes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fullstack-project`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack-project`.`players` (
  `user_id` INT UNIQUE NOT NULL,
  `player_name` VARCHAR(16) CHARACTER SET 'binary' NULL,
  `position_x` FLOAT NOT NULL DEFAULT 0,
  `position_y` FLOAT NOT NULL DEFAULT 0,
  `position_z` FLOAT NOT NULL DEFAULT 0,
  `rotation_x` FLOAT NOT NULL DEFAULT 0,
  `rotation_y` FLOAT NOT NULL DEFAULT 0,
  `rotation_z` FLOAT NOT NULL DEFAULT 0,
  `rotation_w` FLOAT NOT NULL DEFAULT 1,
  `velocity_x` FLOAT NOT NULL DEFAULT 0,
  `velocity_y` FLOAT NOT NULL DEFAULT 0,
  `velocity_z` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  INDEX `fk_player_user_idx` (`user_id` ASC) VISIBLE)
ENGINE = MEMORY;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
